### ISSUE TITLE
Can't copy values from TUI

### ISSUE THREAD

**Issue by thephez** [dashpay/rs-platform-explorer#44]
When using Ubuntu (22.04), I'm unable to copy the receive address ("c") or identity ID ("d"). Pressing the relevant key doesn't result in the requested data being available to paste. The last value I copied before attempting to copy from the TUI remains on the clipboard. This is for the current master branch (373177308444b3156c97049d13e33998d5e7da46).

![image](https://github.com/dashpay/rs-platform-explorer/assets/8145677/4834e458-3961-431f-bb36-0859d118ca0b)

**Comment by qwizzie** [comment]
I came across this problem as well yesterday after a cargo run of TUI, no copy and paste possibility in PUTTY and the C (copy the receive address) inside wallet (W) did not work (pressing C has a tendency to crash TUI). Nor could i enter a private key in a wallet (W) through copy and paste. In the end using Solar-PuTTY instead of PuTTY, i got the copy and paste working for both the receive address and for the private key of a wallet through mouse selection. But the actual copy command (C) still does not work.

**Comment by thephez** [comment]
@fominok, could you take a look at this? I'm still having this issue and Paul suggested mentioning it to you.

**Comment by VirgileBa** [comment]
I also have this issue on the latest ubuntu release.

**Comment by lordbah** [comment]
Seeing this today on PopOS (Ubuntu).
Note: I can paste with Shift-Insert, but I can't copy, in fact can't even highlight the text I would want to copy.

**Comment by thephez** [comment]
For those on Linux (Ubuntu anyway) - I just learned that if I hold Shift, I can then select text with the mouse. At that point Ctrl-Shift-C (terminal copy shortcut key for Ubuntu) works to copy.

Info from ChatGPT:
> The issue with being unable to select text for copy-paste in your terminal application could be related to how the terminal user interface (TUI) library you're using handles input and rendering. You're using tuirealm and tui-realm-stdlib, which render terminal UIs in a way that may prevent native terminal interactions like text selection.
